### PR TITLE
use planetary image and remove gdal requirement

### PR DESCRIPTION
**Pull request by nikhilkalige**

### CODE REVIEW

**Comment by nikhilkalige** [comment]
Fixes #12 #13 #14

**Comment by godber** [comment]
This thing still runs right?

**Comment by godber** [comment]
I setup like this:

```
brew install qt
mkvirtualenv newvenv
pip install -e .
```

Everything appeared to install fine.  But when I run `pdsview` I still get a Qt missing error:

```
Traceback (most recent call last):
  File "/Users/godber/.venvs/pdsview/bin/pdsview", line 9, in <module>
    load_entry_point('pdsview==0.1.0', 'console_scripts', 'pdsview')()
  File "/Users/godber/.venvs/pdsview/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/godber/.venvs/pdsview/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/Users/godber/.venvs/pdsview/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/Users/godber/.venvs/pdsview/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/godber/Workspace/pdsview/pdsview/pdsview.py", line 14, in <module>
    import label
  File "/Users/godber/Workspace/pdsview/pdsview/label.py", line 1, in <module>
    from ginga.qtw.QtHelp import QtGui, QtCore
  File "/Users/godber/.venvs/pdsview/lib/python2.7/site-packages/ginga/qtw/QtHelp.py", line 95, in <module>
    raise ImportError("Failed to import qt4, qt5 or pyside. There may be an issue with the toolkit module or it is not installed")
ImportError: Failed to import qt4, qt5 or pyside. There may be an issue with the toolkit module or it is not installed
```

Did you have to symbolically link qt in to your venv or something?

**Comment by nikhilkalige** [comment]
run `pyside_postinstall.py`

**Comment by godber** [comment]
On linux, I had to do this:

```
python /home/godber/.virtualenvs/newvenv/bin/pyside_postinstall.py -install
```

But ultimately it worked!

-home-godber-msl-sol71-caltargets-0071mr0498008000e1_dxxx img_245

**Pull request merged**
